name: knowunity
publish_to: 'none'
description: Knowunity case study.

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: '>=3.7.7'

dependencies:
  auto_route: ^6.1.0
  cupertino_icons: ^1.0.2
  dio: ^5.0.2
  dio_smart_retry: ^5.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.2.0
  injectable: ^2.1.0
  intl: ^0.17.0
  provider: ^6.0.1

dev_dependencies:
  auto_route_generator: ^6.0.0
  build_runner: ^2.1.4
  flutter_gen_runner: ^5.1.0
  injectable_generator: ^2.1.2
  lint: ^2.0.1

flutter_gen:
  output: lib/common/flutter_gen/

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: SF-Pro-Rounded
      fonts:
        - asset: fonts/SF-Pro-Rounded-Thin.ttf
          weight: 100
        - asset: fonts/SF-Pro-Rounded-Extra-Light.ttf
          weight: 200
        - asset: fonts/SF-Pro-Rounded-Light.ttf
          weight: 300
        - asset: fonts/SF-Pro-Rounded-Regular.ttf
          weight: 400
        - asset: fonts/SF-Pro-Rounded-Medium.ttf
          weight: 500
        - asset: fonts/SF-Pro-Rounded-Semi-Bold.ttf
          weight: 600
        - asset: fonts/SF-Pro-Rounded-Bold.ttf
          weight: 700
        - asset: fonts/SF-Pro-Rounded-Extra-Bold.ttf
          weight: 800
        - asset: fonts/SF-Pro-Rounded-Black.ttf
          weight: 900
