name: knowunity
publish_to: 'none'
description: Knowunity case study.

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: '>=3.7.7'

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.0.2
  dio_smart_retry: ^5.0.0
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  injectable: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.4
  injectable_generator: ^2.1.2
  lint: ^2.0.1

flutter:
  uses-material-design: true
